<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Image Optimization & Profiles</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .navbar {
            margin-bottom: 20px;
        }
        .container {
            padding: 20px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Always Here</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick="navigateTo('optimize')">Image Optimizer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick="navigateTo('profile')">Create Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick="navigateTo('about')">About Us</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div id="content" class="container">
    <!-- Content will be dynamically loaded here -->
</div>

<script>
    function navigateTo(page) {
        const content = document.getElementById('content');
        switch (page) {
            case 'optimize':
                content.innerHTML = `
                    <h1>Image Optimizer</h1>
                    <p>Upload an image of a person to enhance its quality using AI.</p>
                    <form id="optimizeForm">
                        <div class="mb-3">
                            <label for="imageUpload" class="form-label">Upload Image</label>
                            <input type="file" class="form-control" id="imageUpload" accept="image/*">
                        </div>
                        <button type="submit" class="btn btn-primary">Optimize</button>
                    </form>
                    <div id="optimizationResult" class="mt-3"></div>
                `;
                break;
            case 'profile':
                content.innerHTML = `
                    <h1>Create Profile</h1>
                    <p>To save your profile, a one-time fee is required.</p>
                    <form id="profileForm">
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" class="form-control" id="name" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="payment" class="form-label">Payment (Credit Card)</label>
                            <input type="text" class="form-control" id="payment" placeholder="Enter payment details" required>
                        </div>
                        <button type="submit" class="btn btn-success">Pay & Save Profile</button>
                    </form>
                    <div id="profileResult" class="mt-3"></div>
                `;
                break;
            case 'about':
                content.innerHTML = `
                    <h1>About Us</h1>
                    <p>We specialize in AI-driven solutions to optimize images and provide users with a seamless experience for creating personalized profiles.</p>
                    <p>Our mission is to empower creativity through advanced technologies.</p>
                `;
                break;
            default:
                content.innerHTML = '<h1>Welcome to Always Here</h1>';
        }
    }

    // Load default page
    navigateTo('optimize');

    // Event listeners for forms (basic demo purposes)
    document.addEventListener('submit', function (e) {
        e.preventDefault();
        const formId = e.target.id;
        if (formId === 'optimizeForm') {
            document.getElementById('optimizationResult').innerText = 'Image optimized successfully!';
        } else if (formId === 'profileForm') {
            document.getElementById('profileResult').innerText = 'Profile saved successfully! Payment processed.';
        }
    });
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
